"""
Two agents negotiate a deal live. If GROQ_API_KEY is set, the negotiation
lines are generated by an actual LLM call (Groq, llama-3.3-70b-versatile)
reasoning over the two agents' real trust context. If no key is present
(e.g. running this locally without setup), a deterministic scripted
negotiation runs instead so the demo/tests never break.
"""
import os
import json
import httpx
import store
import trust_graph

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"


async def run_negotiation(agent_a_id: str, agent_b_id: str) -> list[dict]:
    """Returns a list of {speaker, text} negotiation turns ending with a clear ACCEPT/REJECT verdict."""
    a = store.agents[agent_a_id]
    b = store.agents[agent_b_id]
    report = trust_graph.trust_report(agent_a_id, agent_b_id)

    if GROQ_API_KEY:
        try:
            return await _llm_negotiation(a, b, report)
        except Exception as e:
            fallback = _scripted_negotiation(a, b, report)
            fallback.append({"speaker": "system", "text": f"(LLM call failed, used scripted fallback: {e})"})
            return fallback

    return _scripted_negotiation(a, b, report)


async def _llm_negotiation(a: dict, b: dict, report: dict) -> list[dict]:
    system_prompt = (
        "You are simulating a short, realistic negotiation between two autonomous AI agents "
        "deciding whether to trust each other enough to complete a transaction. "
        "Use the cryptographic trust context given. Keep it terse — 4 to 6 short lines total, "
        "alternating speakers, then end with exactly one final line starting with 'VERDICT: ACCEPT' "
        "or 'VERDICT: REJECT' plus a short reason. Respond ONLY as a JSON array of objects like "
        '[{"speaker": "ShopBot", "text": "..."}]. No markdown, no extra text.'
    )
    user_prompt = (
        f"Agent A: {a['name']} ({a['bio']})\n"
        f"Agent B: {b['name']} ({b['bio']})\n"
        f"Trust check result: trusted={report['trusted']}, reason={report['reason']}\n"
        "Simulate their negotiation now."
    )

    async with httpx.AsyncClient(timeout=20) as client:
        resp = await client.post(
            GROQ_URL,
            headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.7,
                "max_tokens": 500,
            },
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"]
        content = content.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(content)


def _scripted_negotiation(a: dict, b: dict, report: dict) -> list[dict]:
    turns = [
        {"speaker": a["name"], "text": f"Hi {b['name']}, I'd like to proceed with a transaction. Can you verify your trust chain?"},
        {"speaker": b["name"], "text": "One moment — broadcasting my public key and signature history."},
    ]
    if report["trusted"]:
        hop_text = "directly signed by someone you trust" if report["hops"] == 1 else f"verified through a {report['hops']}-hop signature chain"
        turns.append({"speaker": a["name"], "text": f"Checking the web of trust... {hop_text}. Signature is cryptographically valid."})
        turns.append({"speaker": b["name"], "text": "Great, let's proceed with the deal."})
        turns.append({"speaker": "system", "text": f"VERDICT: ACCEPT — {report['reason']}"})
    else:
        turns.append({"speaker": a["name"], "text": "Checking the web of trust... no verified signature path found from anyone I trust."})
        turns.append({"speaker": b["name"], "text": "I understand — I don't have any attestations yet."})
        turns.append({"speaker": "system", "text": f"VERDICT: REJECT — {report['reason']}"})
    return turns
